// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foornkwqyuolpveynpsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvb3Jua3dxeXVvbHB2ZXlucHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjA4MzksImV4cCI6MjA3NDI5NjgzOX0.1OkXxZFkW3KTAHtVSsgL3_3sb1dxmFh4NrzzBW8TBsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});